apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: synergychat-crawler
  name: synergychat-crawler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: synergychat-crawler
  template:
    metadata:
      labels:
        app: synergychat-crawler
    spec:
      containers:
        - image: bootdotdev/synergychat-crawler:latest
          name: synergychat-crawler-1
          volumeMounts:
            - name: cache-volume
              mountPath: /cache
          envFrom:
            - configMapRef:
                name: synergychat-crawler-configmap
        - image: bootdotdev/synergychat-crawler:latest
          name: synergychat-crawler-2
          volumeMounts:
            - name: cache-volume
              mountPath: /cache
          envFrom:
            - configMapRef:
                name: synergychat-crawler-configmap
          env:
            - name: CRAWLER_PORT
              value: "8001"
        - image: bootdotdev/synergychat-crawler:latest
          name: synergychat-crawler-3
          volumeMounts:
            - name: cache-volume
              mountPath: /cache
          envFrom:
            - configMapRef:
                name: synergychat-crawler-configmap
          env:
            - name: CRAWLER_PORT
              value: "8002"
      volumes:
        - name: cache-volume
          emptyDir: {}
